FROM node:12

WORKDIR /app

  # install JRE for dynamo-offline (required for tests)
RUN apt-get update \
&& apt-get install -y default-jdk \
&& apt-get clean \
&& rm -rf /var/lib/apt/lists/*

  # Install serverless globally
RUN npm i -g serverless
